### PR TITLE
return specified value while call get() but no key associated with the key.

### PR DESCRIPTION
**Pull request by DinoStray**

### CODE REVIEW

**Comment by bblanchon** [comment]
Hi @DinoStray,

Thank you for this pull request.
However, I don't see how it adds anything to [JsonVariant::operator|](https://arduinojson.org/api/jsonvariant/or/).

**Comment by DinoStray** [comment]
this method is more suitiable for oop users,  for example java user

**Comment by bblanchon** [comment]
Hum, I don't know.
Of the two forms, the one with the operator `|` is the clearer:

```c++
value = obj["a"] | "b";
value = obj.get("a", "b");

value = arr[1] | 2;
value = arr.get(1, 2);
```
As a general rule, I try to reduce the number of parameters of functions (especially when they can have the same type) because it's not clear what's the role of each. In ArduinoJson, there very few methods with two (or more) parameters.

Let's keep this PR opened, and we'll see how other users react.

**Comment by bblanchon** [comment]
Here is another thing that bothers me about this syntax.

In order to be consistent, we would need to implement a similar feature in `JsonVariant::as<T>()`, which would be:

```c++
value = obj["a"].as<const char*>("b");
```

The meaning is unclear, but more importantly, the template parameter becomes optional, leading to the following:

```c++
value = obj["a"].as("b");
```

Now we completely lost the meaning of `as<T>()`.

Of course, we could only implement this syntax for `get<T>()`, but I think this is a sign that it's not aligned with the design of ArduinoJson.

**Comment by bblanchon** [comment]
I'm sorry @DinoStray; it's been two months and nobody commented or upvoted this PR.
It's time to close it.
Thank you for your comprehension.

**Pull request closed without merging**
