### PR TITLE
Compile under esp-idf new build sysytem

### PR DESCRIPTION
**Pull request by qt1**
This is a non intrusive addition to CMmakeLists.txt that enables using as esp-idf component with the new build system.

For more details please see:

https://github.com/espressif/esp-idf/issues/7024

### CODE REVIEW

**Comment by bblanchon** [comment]
Hi @qt1,

Thank you very much for this PR :+1:

Can you confirm that you tested the patch and that it works as expected?
Do you think it's possible to include the esp-idf component build in the continuous integration?
If so, can you add it yourself or give me some guidance?

Best regards,
Benoit

**Comment by qt1** [comment]
Hi,

I can confirm that the errors from the build system are resolved.

I did not test the code itself as there are other, unrelated, errors to the build. 
However since this is a header only component I assume that everything that used to work will continue to work.

Unfortunately I am not familiar with CI. Maybe [@projectgus](https://github.com/projectgus) , who actually resolved this issue, can help.

**Comment by bblanchon** [comment]
I'll wait until you can confirm that this patch is fully functional, useful, and necessary.
The library is already bloated with many platform-specific hacks that I must maintain just in case; I prefer to think twice before adding a new one.

Moreover, I don't understand the motivation since ArduinoJson already implements good practices for CMake (as far as I know), supporting `FetchContent` and `find_library` (see [How to use ArduinoJson with CMake?](https://arduinojson.org/v6/how-to/use-arduinojson-with-cmake/)).

**Comment by andreaskuster** [comment]
@bblanchon
I added a ci build pipeline that compiles all examples in ArduinoJson/examples in the esd-idf environment (with ArduinoJson as a component).  Please approve the execution such that i can test its functionality (it works offline, but that is never a guarantee).

Functionality: It works locally, and we will soon see it working with the new ci pipeline step added.

Usefullness & Necessary: Well, I would like to see this functionality added. It is **the** way of handling ESP32 + Arduino projects with proper Cmake (i.e. without platformio or arduino IDE), which in my opinion is a lot nicer. I would use this functionality in here: https://github.com/andreaskuster/ESP32-WebCam in conjunction with the ESPAsyncWebServer. 

About the motivation of using this extra build structure instead of the standard CMake find_library functionality: I totally agree with you that I do not understand why they cannot use the standard `find_package` functionality. I guess they will have their reasons for that and there is not much we can change. Here you can find the documentation about this component build system from their official documentation: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#minimal-component-cmakelists

**Pull request closed without merging**
