### PR TITLE
Added Arduino Library Manager Badge (ArduBadge)

### PR DESCRIPTION
**Pull request by gilmaimon**
Added ArduBadge Badge to the readme file.
ArduBadge: http://www.ardu-badge.com/

The badge shows the latest version available on the Arduino IDE Library Manager and also show instructions on installing via the Library Manager and via a ZIP file (with automatic link to the latest release ZIP).

### CODE REVIEW

**Comment by bblanchon** [comment]
Hi @gilmaimon,

That's very cool!
However, there is one problem: it displays 6.7.0-beta on the README for the master branch, which contains version 5.13.4.

Regards,
Benoit

**Comment by gilmaimon** [comment]
> Hi @gilmaimon,
> 
> That's very cool!
> However, there is one problem: it displays 6.7.0-beta on the README for the master branch, which contains version 5.13.4.
> 
> Regards,
> Benoit

Tnx!
Yea, ArduBadge shows the latest version available on the Library Manager (without considering current branch). I can work on a feature where it will only show latest stable release (latest version not marked as "beta"). Would you like that?

**Comment by gilmaimon** [comment]
@bblanchon, specifying the version in the URL kinda misses the point of the badge being dynamic, but it might be suitable for some users.. Another way to do it could be to specify the branch the badge is in. So for master it will always show the latest stable release.
Currently this is not implemented, I will make a request when it is available.

**Comment by gilmaimon** [comment]
> @gilmaimon I really don't understand why the badge has to be dynamic. A version in the URL is already more than I need.

Cool! So here it is:
[arduino-library-badge](https://www.ardu-badge.com/ArduinoJson/5.13.4)
Markdown:
`[arduino-library-badge](https://www.ardu-badge.com/ArduinoJson/5.13.4)`
The version is specified in the urls :)

**Comment by bblanchon** [comment]
That looks good to me.
Please update the pull request so I can merge it.

**Comment by gilmaimon** [comment]
> That looks good to me.
> Please update the pull request so I can merge it.

Great. I cannot edit this pull request, so I opened a new one:
https://github.com/bblanchon/ArduinoJson/pull/895
That one having the updated badge.
Thank You.

**Comment by bblanchon** [comment]
You can edit a pull request.
You just need to push more commits to the same branch.

**Comment by gilmaimon** [comment]
> You can edit a pull request.
> You just need to push more commits to the same branch.

I deleted that fork (this pull request) from my profile so this branch became read only.
#895 the fixed changes and also is still on my active forks, so I can change it for any reason that may come up.

**Pull request closed without merging**
