### PR TITLE
Continuous Fuzzing Integration with Fuzzit

### PR DESCRIPTION
**Pull request by yevgenypats**
@bblanchon The Pull-request is ready. Please review.

Currently there are two long running fuzzing job on [Fuzzit](https://app.fuzzit.dev) + every commit sanity tests with the generated test cases by the fuzzers.

I dedicated 6 CPUs and 12 GB ram for this project.

You need to signup for https://app.fuzzit.dev and I'll add you to the ArduinoJson project on Fuzzit.

If any crashes will pop should I configure to send alerts to your email?

Best,
Yevgeny

### CODE REVIEW

**Comment by bblanchon** [comment]
Hi @yevgenypats,

I logged in with my GitHub credentials, what's the next step?

Best Regards,
Benoit

**Comment by yevgenypats** [comment]
hi @bblanchon!
I've added you the arduinojson account https://app.fuzzit.dev/orgs/arduinojson/dashboard.

I think this PR need an update as a lot of features and bugfixes where added in the mean-time. if you are willing to merge/use this then I'll update the PR.

**Comment by bblanchon** [comment]
Yes, I plan to merge the PR, but I'd like to get a look at Fuzzit first.
Right now the dashboard seems empty, is that expected?

**Comment by yevgenypats** [comment]
Yes, because I just opened this account. I'll push an update to this PR now.

**Comment by bblanchon** [comment]
Any chance we might get this work?
Otherwise, I prefer closing the PR...

**Pull request closed without merging**
