### PR TITLE
Add CIFuzz

### PR DESCRIPTION
**Pull request by AdamKorcz**
Adds [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/). This will run the fuzzers during pull requests for 600 seconds. The time can be modified.

CIFuzz is an addition to ArduinoJson's OSS-fuzz integration. The documentation for CIFuzz can be found here: https://google.github.io/oss-fuzz/getting-started/continuous-integration/

The existing fuzzers are found here: https://github.com/bblanchon/ArduinoJson/tree/6.x/extras/fuzzing

### CODE REVIEW

**Comment by bblanchon** [comment]
Thanks, @AdamKorcz; I didn't know about CIFuzz.
I'm already fuzzing the library [as part of the CTest run](https://github.com/bblanchon/ArduinoJson/blob/6.x/extras/fuzzing/CMakeLists.txt#L43-L53), but CIFuzz seems to offer a cleaner solution, so I think I'll remove that.
Also, I think it makes sense to run CIFuzz after all builds succeeded and not in parallel.
Do you mind if I alter your PR before merging it?

**Comment by AdamKorcz** [comment]
> Do you mind if I alter your PR before merging it?

Not at all.

**Comment by bblanchon** [comment]
@AdamKorcz, I noticed you created the same PR in dozens of repositories; what's up with that?

**Comment by AdamKorcz** [comment]
@bblanchon I am a contributor to OSS-fuzz and fuzzing of open source software in general.

See list of OSS-fuzz contributors: https://github.com/google/oss-fuzz/graphs/contributors

See also https://adalogics.com/blog/fuzzing-100-open-source-projects-with-oss-fuzz for reference

**Comment by bblanchon** [comment]
> Once you have completed an integration OSS-Fuzz offers an integration reward of 500-1000 USD. This is a nice reward for your work, and following the non-trivial effort of integrating your project it is of great pleasure to receive a monetary award.

Given that you created the same PR on the following repos, I'm wondering if you're only looking after the reward 😲

1. https://github.com/libass/libass/pull/568
2. https://github.com/vitessio/vitess/pull/9084
3. https://github.com/libgit2/libgit2/pull/6098
4. https://github.com/libarchive/libarchive/pull/1604
5. https://github.com/libjpeg-turbo/libjpeg-turbo/pull/559
6. https://github.com/grpc-ecosystem/grpc-gateway/pull/2405

Can you confirm that you will not receive any financial reward for these PRs?

**Pull request closed without merging**
