### PR TITLE
alloc override

### PR DESCRIPTION
**Pull request by jefffhaynes**
added override to StaticJsonBuffer::alloc.  Hope you don't mind, I enforce override on my projects :)

### CODE REVIEW

**Comment by bblanchon** [comment]
Hi @jefffhaynes,

No, I don't mind.
In fact, I use `override` in all my modern C++ code; except that ArduinoJson must be compatible with C++98.

How do you enforce this?
Do you have a compiler warning or some kind of static analysis?

I can add a macro that will expand to `override` or nothing depending on the C++ standard.
Would that pass your test?

Regards,
Benoit

**Comment by bblanchon** [comment]
PS: ArduinoJson 6 doesn't use any `virtual`, maybe that's a better option for you.

**Comment by jefffhaynes** [comment]
Yeah sorry I didn’t realize the bit about C++98. A macro would be perfect. I simply make the warning an error on our projects.

Thanks for the great library.

Jeff


________________________________

**Comment by bblanchon** [comment]
What is the name of the warning?
I'll try to trigger it on the continuous integration.

**Comment by jefffhaynes** [comment]
Weirdly I can’t find how I did it now. I’ll have to look when I’m back at work.

Thanks



________________________________

**Pull request closed without merging**
