### PR TITLE
Add .mbedignore file, exclude test code from mbed OS firmware.

### PR DESCRIPTION
**Pull request by nuket**
Without this `.mbedignore` file, the bulk of the ArduinoJson `test/*` code gets pulled into the mbed OS build process, which causes the final firmware to be too large for the target processor, since most off-the-shelf embedded processors have somewhere between 128 - 256KB of flash. 

When running `mbed compile` without this file, the linker errors out unhappily:

> ./mbed-os/hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TOOLCHAIN_GCC_ARM/TARGET_MCU_NORDIC_32K/NRF51822.ld:142 cannot move location counter backwards (from 0000000020007fe0 to 0000000020007800)
> collect2: error: ld returned 1 exit status
> [ERROR] ./mbed-os/hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TOOLCHAIN_GCC_ARM/TARGET_MCU_NORDIC_32K/NRF51822.ld:142 cannot move location counter backwards (from 0000000020007fe0 to 0000000020007800)
> collect2: error: ld returned 1 exit status

With the `.mbedignore` file, everything is fine.

I also reported this issue as - https://github.com/ARMmbed/mbed-os/issues/2467

### CODE REVIEW

**Comment by bblanchon** [comment]
Hi Max,

Thank you very much for this contribution 👍 

I think that this file should be in the root folder, along with `.gitignore`.

Also, I think you should also add other folders:

```
/.github/
/scripts/
/tests/
/third-party/
```

And probably unwanted files in the root folder.

Would that work?

Regards,
Benoit

**Comment by bblanchon** [comment]
@nuket Did you see my message above?

**Comment by nuket** [comment]
Yes, I will try this out.

**Comment by nuket** [comment]
Ok, I've added the folders above, looks good.

**Comment by bblanchon** [comment]
Manually merged in a7ef99d0fe29ff090fafb586f306612309aabebf

**Pull request closed without merging**
