### PR TITLE
README Link Cleanup

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
- Replaced all direct links with references.
- Moved banner into resource folder.

### CODE REVIEW

**Comment by bblanchon** [comment]
Hi @ElectronicsArchiver,

Thank you for this contribution.
I have one question though: **why?**

Best regards,
Benoit

**Comment by ElectronicsArchiver** [comment]
> Hi @ElectronicsArchiver,
> 
> Thank you for this contribution. I have one question though: **why?**
> 
> Best regards, Benoit

- Abstracting links makes the text that uses theses links more readable
- Helps structure markdown files by separating lexical / meta data
- Makes it easier to update links as they are all in one known place
- Gives links names by which they can be found

**Comment by bblanchon** [comment]
To be honest, I find your arguments very farfetched, but since you made the effort of writing them, I'll answer each point.

> Abstracting links makes the text that uses these links more readable

...but makes you scroll at the bottom of the document to file the URL

> Helps structure markdown files by separating lexical / meta data

Even if we admit this argument makes sense for some people, I still find that keeping a link and the URL together is more convenient to write and read.

> Makes it easier to update links as they are all in one known place

Above all, it makes it easier to make mistakes when you add new links.

> Gives links names by which they can be found

Found how? Why would you have to find them anyway?

**Comment by ElectronicsArchiver** [comment]
I did not expect this to be a lost cause, how unfortunate ..

**Comment by bblanchon** [comment]
I understand your frustration, and I'm sorry I had to turn your PR down, but ultimately, I'm the one who will have to maintain this README file for (hopefully) years to come.
Before making a PR, it's always good to probe the owner's opinion by opening an issue first.

**Pull request closed without merging**
